-- GENERATED by warehouse/build_schema.py — do not edit by hand.
-- Every table and column below is referenced by a cube in model/cubes/.
-- Targets DuckDB (the default local warehouse); see warehouse/README.md to retarget.

CREATE SCHEMA IF NOT EXISTS core_billing;
CREATE SCHEMA IF NOT EXISTS core_customer;
CREATE SCHEMA IF NOT EXISTS core_funnel;
CREATE SCHEMA IF NOT EXISTS core_orders;
CREATE SCHEMA IF NOT EXISTS core_product;
CREATE SCHEMA IF NOT EXISTS core_quotes;
CREATE SCHEMA IF NOT EXISTS core_rep;
CREATE SCHEMA IF NOT EXISTS core_sales;
CREATE SCHEMA IF NOT EXISTS mart_appliances;
CREATE SCHEMA IF NOT EXISTS mart_electronics;
CREATE SCHEMA IF NOT EXISTS mart_furniture;
CREATE SCHEMA IF NOT EXISTS mart_growth;
CREATE SCHEMA IF NOT EXISTS mart_pipeline;
CREATE SCHEMA IF NOT EXISTS mart_suppliers;

CREATE TABLE IF NOT EXISTS core_billing.annual_renewal_cycles (
  commission_last_12m  NUMERIC,
  cycle_id             STRING,
  cycle_value          NUMERIC,
  expected_renewal_at  TIMESTAMP,
  expiry_status        STRING,
  renewal_status       STRING,
  renewed_at           TIMESTAMP,
  rep_id               STRING,
  started_at           TIMESTAMP
);

CREATE TABLE IF NOT EXISTS core_billing.subscription_charges_invoices (
  charge_amount          NUMERIC,
  charge_id              STRING,
  charge_status          STRING,
  competence_date        TIMESTAMP,
  due_date               TIMESTAMP,
  id                     STRING,
  invoice_amount         NUMERIC,
  invoice_id             STRING,
  invoice_status         STRING,
  is_primary_charge_row  BOOL,
  payer_name             STRING,
  payer_tax_id           STRING,
  payment_method         STRING,
  plan                   STRING,
  rep_id                 STRING,
  settled_at             TIMESTAMP
);

CREATE TABLE IF NOT EXISTS core_customer.customer_overview (
  company_name  STRING,
  created_at    TIMESTAMP,
  customer_id   STRING,
  industry      STRING,
  is_active     BOOL,
  segment       STRING,
  state         STRING
);

CREATE TABLE IF NOT EXISTS core_funnel.journey_funnel (
  approved_order_id  STRING,
  cohort_month       STRING,
  journey_id         STRING,
  order_id           STRING,
  product_line       STRING,
  quote_id           STRING,
  sale_order_id      STRING,
  started_at         TIMESTAMP
);

CREATE TABLE IF NOT EXISTS core_orders.orders_overview (
  assumed_value    NUMERIC,
  created_at       TIMESTAMP,
  customer_id      STRING,
  order_id         STRING,
  parent_order_id  STRING,
  product_id       NUMERIC,
  product_line     STRING,
  rep_id           STRING,
  status_category  STRING
);

CREATE TABLE IF NOT EXISTS core_product.product_overview (
  category           STRING,
  is_active          BOOL,
  list_price         NUMERIC,
  parent_product_id  STRING,
  product_id         NUMERIC,
  product_line       STRING,
  product_name       STRING,
  supplier_id        STRING
);

CREATE TABLE IF NOT EXISTS core_quotes.quotes_base (
  customer_id   STRING,
  order_id      STRING,
  product_line  STRING,
  quote_id      STRING,
  quoted_at     TIMESTAMP,
  quoted_value  NUMERIC,
  rep_id        STRING
);

CREATE TABLE IF NOT EXISTS core_rep.lead_status_changes (
  change_id    STRING,
  changed_at   TIMESTAMP,
  from_status  STRING,
  lead_id      STRING,
  to_status    STRING
);

CREATE TABLE IF NOT EXISTS core_rep.portal_logins_monthly (
  active_days      NUMERIC,
  logins_in_month  NUMERIC,
  reference_month  TIMESTAMP,
  rep_id           STRING
);

CREATE TABLE IF NOT EXISTS core_rep.recruitment_leads (
  channel           STRING,
  converted_at      TIMESTAMP,
  created_at        TIMESTAMP,
  lead_id           STRING,
  lead_score        NUMERIC,
  rejection_reason  STRING,
  rep_id            STRING,
  status            STRING
);

CREATE TABLE IF NOT EXISTS core_rep.rep_commercial_events (
  amount        NUMERIC,
  customer_id   STRING,
  event_date    TIMESTAMP,
  event_id      STRING,
  event_type    STRING,
  product_line  STRING,
  rep_id        STRING
);

CREATE TABLE IF NOT EXISTS core_rep.rep_overview (
  account_manager      STRING,
  billing_customer_id  STRING,
  city                 STRING,
  cohort               STRING,
  company_id           STRING,
  crm_contact_id       STRING,
  email                STRING,
  exit_date            TIMESTAMP,
  full_name            STRING,
  last_portal_login    TIMESTAMP,
  lead_tier            STRING,
  onboarding_date      TIMESTAMP,
  phone                STRING,
  plan                 STRING,
  region               STRING,
  rep_id               STRING,
  rep_score            NUMERIC,
  rep_status           STRING,
  state                STRING,
  tax_id               STRING,
  territory            STRING,
  tier                 STRING
);

CREATE TABLE IF NOT EXISTS core_sales.commission_ledger (
  base_amount        NUMERIC,
  booked_at          TIMESTAMP,
  commission_amount  NUMERIC,
  commission_id      STRING,
  installment        NUMERIC,
  product_line       STRING,
  rep_id             STRING,
  sale_id            STRING,
  settled_at         TIMESTAMP,
  settlement_status  STRING
);

CREATE TABLE IF NOT EXISTS core_sales.sales_summary (
  channel                    STRING,
  commission_company_amount  NUMERIC,
  commission_rep_amount      NUMERIC,
  commission_total_amount    NUMERIC,
  customer_id                STRING,
  is_new_customer            BOOL,
  product_id                 NUMERIC,
  product_line               STRING,
  rep_id                     STRING,
  sale_amount                NUMERIC,
  sale_id                    STRING,
  sold_at                    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mart_appliances.deal_pipeline (
  closed_at              TIMESTAMP,
  created_at             TIMESTAMP,
  customer_id            STRING,
  deal_amount            NUMERIC,
  deal_id                STRING,
  installation_required  BOOL,
  lost_reason            STRING,
  rep_id                 STRING,
  stage_name             STRING,
  status                 STRING,
  warranty_months        NUMERIC
);

CREATE TABLE IF NOT EXISTS mart_appliances.rep_ranking_monthly (
  production_amount  NUMERIC,
  production_score   NUMERIC,
  quartile           STRING,
  rank_position      NUMERIC,
  reference_month    TIMESTAMP,
  rep_id             STRING
);

CREATE TABLE IF NOT EXISTS mart_electronics.deal_pipeline (
  closed_at       TIMESTAMP,
  created_at      TIMESTAMP,
  customer_id     STRING,
  deal_amount     NUMERIC,
  deal_id         STRING,
  is_bundle       BOOL,
  lost_reason     STRING,
  rep_id          STRING,
  stage_name      STRING,
  status          STRING,
  trade_in_value  NUMERIC
);

CREATE TABLE IF NOT EXISTS mart_electronics.rep_ranking_monthly (
  production_amount  NUMERIC,
  production_score   NUMERIC,
  quartile           STRING,
  rank_position      NUMERIC,
  reference_month    TIMESTAMP,
  rep_id             STRING
);

CREATE TABLE IF NOT EXISTS mart_furniture.deal_pipeline (
  closed_at        TIMESTAMP,
  created_at       TIMESTAMP,
  customer_id      STRING,
  deal_amount      NUMERIC,
  deal_id          STRING,
  is_custom_order  BOOL,
  lead_time_days   NUMERIC,
  lost_reason      STRING,
  rep_id           STRING,
  stage_name       STRING,
  status           STRING
);

CREATE TABLE IF NOT EXISTS mart_furniture.rep_ranking_monthly (
  production_amount  NUMERIC,
  production_score   NUMERIC,
  quartile           STRING,
  rank_position      NUMERIC,
  reference_month    TIMESTAMP,
  rep_id             STRING
);

CREATE TABLE IF NOT EXISTS mart_growth.rep_ramp_up (
  acquisition_channel  STRING,
  days_to_target       NUMERIC,
  first_order_at       TIMESTAMP,
  first_sale_at        TIMESTAMP,
  last_order_at        TIMESTAMP,
  lifetime_orders      NUMERIC,
  lifetime_sales       NUMERIC,
  ramp_group           STRING,
  reached_target_at    TIMESTAMP,
  rep_id               STRING
);

CREATE TABLE IF NOT EXISTS mart_pipeline.deal_pipeline_template (
  closed_at    TIMESTAMP,
  created_at   TIMESTAMP,
  customer_id  STRING,
  deal_amount  NUMERIC,
  deal_id      STRING,
  lost_reason  STRING,
  rep_id       STRING,
  stage_name   STRING,
  status       STRING
);

CREATE TABLE IF NOT EXISTS mart_suppliers.supplier_performance_monthly (
  avg_lead_time_days  NUMERIC,
  country             STRING,
  defective_units     NUMERIC,
  delivered_on_time   NUMERIC,
  product_line        STRING,
  purchase_amount     NUMERIC,
  received_units      NUMERIC,
  reference_month     TIMESTAMP,
  supplier_id         STRING,
  supplier_name       STRING,
  total_deliveries    NUMERIC
);
